version: '3'

services:
  db-postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
  pgAdmin:
    depends_on:
      - db-postgres
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com  
      PGADMIN_DEFAULT_PASSWORD: 123456

volumes:
  postgres-db:
    external: false